version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: wallet-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"